
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed5;

	private global::Gtk.Fixed fixed6;

	private global::Gtk.Label PoS;

	private global::Gtk.Fixed fixed7;

	private global::Gtk.Label Camera;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed5 = new global::Gtk.Fixed();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.fixed6 = new global::Gtk.Fixed();
		this.fixed6.WidthRequest = 87;
		this.fixed6.HeightRequest = 72;
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.PoS = new global::Gtk.Label();
		this.PoS.Name = "PoS";
		this.PoS.LabelProp = global::Mono.Unix.Catalog.GetString("PoS");
		this.fixed6.Add(this.PoS);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.PoS]));
		w1.X = 32;
		w1.Y = 20;
		this.fixed5.Add(this.fixed6);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.fixed6]));
		w2.X = 13;
		w2.Y = 11;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.fixed7 = new global::Gtk.Fixed();
		this.fixed7.WidthRequest = 135;
		this.fixed7.HeightRequest = 135;
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.Camera = new global::Gtk.Label();
		this.Camera.Name = "Camera";
		this.Camera.LabelProp = global::Mono.Unix.Catalog.GetString("Camera");
		this.fixed7.Add(this.Camera);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.Camera]));
		w3.X = 46;
		w3.Y = 51;
		this.fixed5.Add(this.fixed7);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.fixed7]));
		w4.X = 131;
		w4.Y = 10;
		this.Add(this.fixed5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
